version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: memory_system_demo
      POSTGRES_USER: memory_system
      POSTGRES_PASSWORD: memory_system_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: memory_system_demo
      MONGO_INITDB_ROOT_USERNAME: memory_system
      MONGO_INITDB_ROOT_PASSWORD: memory_system_pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
